import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PortableText } from "@portabletext/react";
import { sanityClient } from "@/lib/sanity/client";
import { urlFor } from "@/lib/sanity/image";
import type { Metadata } from "next";

export const revalidate = 300;

async function getArticle(slug: string) {
  return sanityClient.fetch(
    `*[_type == "newsArticle" && slug.current == $slug][0]{
      _id, title, slug, excerpt, heroImage, brand, publishedAt,
      body, autoGenerated, source
    }`,
    { slug }
  );
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const a = await getArticle(params.slug);
  if (!a) return { title: "Article Not Found" };
  return {
    title: `${a.title} | A Sneaker Life`,
    description: a.excerpt ?? `Read the latest on ${a.title} at A Sneaker Life.`,
    openGraph: {
      title: a.title,
      description: a.excerpt,
      images: a.heroImage ? [{ url: urlFor(a.heroImage).width(1200).height(630).url() }] : [],
    },
  };
}

export async function generateStaticParams() {
  const articles = await sanityClient.fetch(
    `*[_type == "newsArticle" && status == "published"]{ slug }`
  );
  return articles
    .map((a: any) => ({ slug: a.slug?.current }))
    .filter((a: any) => a.slug);
}

export default async function NewsArticlePage({ params }: { params: { slug: string } }) {
  const a = await getArticle(params.slug);
  if (!a) notFound();

  return (
    <div className="min-h-screen bg-[#fafafa] dark:bg-[#111]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
        {/* Breadcrumb */}
        <nav className="text-xs text-gray-400 uppercase tracking-widest mb-6 flex gap-2">
          <Link href="/" className="hover:text-gray-900 dark:hover:text-white transition-colors">Home</Link>
          <span>/</span>
          <Link href="/news" className="hover:text-gray-900 dark:hover:text-white transition-colors">News</Link>
          <span>/</span>
          <span className="text-gray-600 dark:text-gray-300 truncate max-w-[200px]">{a.title}</span>
        </nav>

        {/* Brand tag */}
        {a.brand && (
          <span className="inline-block text-[10px] uppercase tracking-widest text-white bg-gray-900 dark:bg-white dark:text-gray-900 px-2 py-0.5 rounded-full mb-3">
            {a.brand}
          </span>
        )}

        {/* Title */}
        <h1 className="text-2xl sm:text-3xl font-black uppercase tracking-tight text-gray-900 dark:text-white mb-3">
          {a.title}
        </h1>

        {/* Date */}
        <p className="text-xs text-gray-400 uppercase tracking-widest mb-8">
          {new Date(a.publishedAt).toLocaleDateString("en-US", {
            weekday: "long",
            month: "long",
            day: "numeric",
            year: "numeric",
          })}
        </p>

        {/* Hero image */}
        {a.heroImage && (
          <div className="relative w-full aspect-video rounded-xl overflow-hidden bg-gray-100 dark:bg-[#222] mb-8">
            <Image
              src={urlFor(a.heroImage).width(1200).height(675).url()}
              alt={a.title}
              fill
              priority
              sizes="(max-width: 768px) 100vw, 896px"
              className="object-cover"
            />
          </div>
        )}

        {/* Body content */}
        {a.body && (
          <div className="prose prose-sm dark:prose-invert max-w-none mb-10 prose-headings:uppercase prose-headings:tracking-tight prose-headings:font-black prose-p:text-gray-600 dark:prose-p:text-gray-300 prose-p:leading-relaxed prose-a:text-gray-900 dark:prose-a:text-white prose-a:underline">
            <PortableText value={a.body} />
          </div>
        )}

        {/* Source attribution */}
        {a.source?.url && (
          <div className="border-t border-gray-200 dark:border-[#333] pt-6 mb-6">
            <p className="text-xs text-gray-400">
              Source:{" "}
              <a
                href={a.source.url}
                target="_blank"
                rel="nofollow noopener noreferrer"
                className="text-gray-900 dark:text-white underline hover:opacity-70 transition-opacity"
              >
                {a.source.name || a.source.url}
              </a>
            </p>
          </div>
        )}

        {/* AI disclosure */}
        {a.autoGenerated && (
          <p className="text-[10px] text-gray-400 italic">
            This article was written with AI assistance
          </p>
        )}
      </div>
    </div>
  );
}
