import { defineField, defineType } from "sanity";

export const newsArticle = defineType({
  name: "newsArticle",
  title: "News Article",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (Rule) => Rule.required() }),
    defineField({ name: "excerpt", title: "Excerpt", type: "text", rows: 3 }),
    defineField({ name: "body", title: "Body", type: "array", of: [{ type: "block" }] }),
    defineField({ name: "heroImage", title: "Hero Image URL", type: "url" }),
    defineField({
      name: "customImage",
      title: "Custom Image",
      type: "image",
      options: { hotspot: true },
      description: "Optional: upload a custom image to override the default",
    }),
    defineField({ name: "brand", title: "Brand", type: "string" }),
    defineField({ name: "tags", title: "Tags", type: "array", of: [{ type: "string" }], options: { layout: "tags" } }),
    defineField({
      name: "source",
      title: "Source",
      type: "object",
      fields: [
        { name: "name", title: "Name", type: "string" },
        { name: "url", title: "URL", type: "url" },
      ],
    }),
    defineField({ name: "publishedAt", title: "Published At", type: "datetime" }),
    defineField({ name: "autoGenerated", title: "Auto Generated", type: "boolean", initialValue: true }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: { list: ["draft", "published"], layout: "radio" },
      initialValue: "published",
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "brand" },
  },
});
