import { defineField, defineType } from "sanity";

export const newsArticle = defineType({
  name: "newsArticle",
  title: "News Article",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      description: "Preview text for cards",
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "url",
      description: "External image URL from source",
    }),
    defineField({
      name: "brand",
      title: "Brand",
      type: "string",
      description: "Primary brand mentioned",
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "source",
      title: "Source",
      type: "object",
      description: "Original article attribution",
      fields: [
        defineField({
          name: "name",
          title: "Source Name",
          type: "string",
        }),
        defineField({
          name: "url",
          title: "Source URL",
          type: "url",
        }),
      ],
    }),
    defineField({
      name: "publishedAt",
      title: "Published At",
      type: "datetime",
    }),
    defineField({
      name: "autoGenerated",
      title: "Auto Generated",
      type: "boolean",
      description: "Flag for AI-written vs manual",
      initialValue: true,
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: {
        list: [
          { title: "Draft", value: "draft" },
          { title: "Published", value: "published" },
        ],
      },
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "brand" },
  },
});
