import { defineField, defineType } from "sanity";

export const review = defineType({
  name: "review",
  title: "Review",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (Rule) => Rule.required() }),
    defineField({ name: "youtubeId", title: "YouTube Video ID", type: "string" }),
    defineField({ name: "thumbnailUrl", title: "Thumbnail URL", type: "url" }),
    defineField({
      name: "customImage",
      title: "Custom Image",
      type: "image",
      options: { hotspot: true },
      description: "Optional: upload a custom image to override the default",
    }),
    defineField({ name: "brand", title: "Brand", type: "string" }),
    defineField({ name: "shoeName", title: "Shoe Name", type: "string" }),
    defineField({ name: "rating", title: "Rating (1-10)", type: "number" }),
    defineField({ name: "summary", title: "AI Summary", type: "text", rows: 4 }),
    defineField({ name: "pros", title: "Pros", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "cons", title: "Cons", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "verdict", title: "Verdict", type: "text", rows: 2 }),
    defineField({ name: "retailPrice", title: "Retail Price", type: "number" }),
    defineField({ name: "affiliateLinks", title: "Buy Links", type: "array", of: [{
      type: "object",
      fields: [
        { name: "retailer", title: "Retailer", type: "string" },
        { name: "url", title: "URL", type: "url" },
      ]
    }]}),
    defineField({ name: "publishedAt", title: "Published At", type: "datetime" }),
    defineField({ name: "autoGenerated", title: "Auto Generated", type: "boolean", initialValue: true }),
  ],
  preview: {
    select: { title: "title", subtitle: "brand" },
  },
});
